# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GymBud' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GymBud
pod 'lottie-ios'
pod 'Alamofire', '~> 5.0.0-rc.3'

  target 'GymBudTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GymBudUITests' do
    # Pods for testing
  end

end
